export const SUPER_ADMIN_ROLE_NAME = "SUPER_ADMIN";
export const ADMIN_ROLE_NAME = "ADMIN";
export const MANAGER_ROLE_NAME = "MANAGER";
export const SALES_ROLE_NAME = "SALES";
export const PURCHASING_ROLE_NAME = "PURCHASING";
export const WAREHOUSE_ROLE_NAME = "WAREHOUSE";
export const PRODUCTION_ROLE_NAME = "PRODUCTION";
export const INSTALLATION_ROLE_NAME = "INSTALLATION";
export const ACCOUNTING_ROLE_NAME = "ACCOUNTING";
export const READ_ONLY_ROLE_NAME = "READ_ONLY";

export const ERP_ROLE_NAMES = [
  SUPER_ADMIN_ROLE_NAME,
  ADMIN_ROLE_NAME,
  MANAGER_ROLE_NAME,
  SALES_ROLE_NAME,
  PURCHASING_ROLE_NAME,
  WAREHOUSE_ROLE_NAME,
  PRODUCTION_ROLE_NAME,
  INSTALLATION_ROLE_NAME,
  ACCOUNTING_ROLE_NAME,
  READ_ONLY_ROLE_NAME,
] as const;

export type ErpRoleName = (typeof ERP_ROLE_NAMES)[number];

export type PermissionDefinition = {
  description: string;
  key: string;
  label: string;
};

export type PermissionGroupDefinition = {
  key: string;
  label: string;
  permissions: readonly PermissionDefinition[];
};

const definePermissions = (
  groupKey: string,
  groupLabel: string,
  permissions: Array<[key: string, label: string, description: string]>,
): PermissionGroupDefinition => {
  return {
    key: groupKey,
    label: groupLabel,
    permissions: permissions.map(([key, label, description]) => ({
      description,
      key,
      label,
    })),
  };
};

export const PERMISSION_GROUPS = [
  definePermissions("system", "Sistema", [
    ["system.users.read", "Ver usuarios", "Permite consultar usuarios y sus asignaciones."],
    ["system.users.create", "Crear usuarios", "Permite crear cuentas de usuario."],
    ["system.users.update", "Actualizar usuarios", "Permite editar cuentas de usuario."],
    ["system.users.delete", "Eliminar usuarios", "Permite eliminar cuentas de usuario."],
    ["system.roles.read", "Ver roles", "Permite consultar roles y asignaciones de permisos."],
    ["system.roles.update", "Actualizar roles", "Permite administrar permisos de los roles."],
    ["system.settings.read", "Ver configuración", "Permite consultar la configuración global del ERP."],
    ["system.settings.update", "Actualizar configuración", "Permite actualizar la configuración global del ERP."],
    ["system.audit.read", "Ver auditoría", "Permite consultar la trazabilidad inmutable de cambios."],
  ]),
  definePermissions("suppliers", "Proveedores", [
    ["suppliers.read", "Ver proveedores", "Permite consultar registros de proveedores."],
    ["suppliers.create", "Crear proveedores", "Permite crear registros de proveedores."],
    ["suppliers.update", "Actualizar proveedores", "Permite editar registros de proveedores."],
    ["suppliers.delete", "Eliminar proveedores", "Permite eliminar registros de proveedores."],
  ]),
  definePermissions("materials", "Materiales", [
    ["materials.read", "Ver materiales", "Permite consultar registros de materiales."],
    ["materials.create", "Crear materiales", "Permite crear registros de materiales."],
    ["materials.update", "Actualizar materiales", "Permite editar registros de materiales."],
    ["materials.delete", "Eliminar materiales", "Permite eliminar registros de materiales."],
  ]),
  definePermissions("price_lists", "Listas de precios", [
    ["price_lists.read", "Ver listas de precios", "Permite consultar listas de precios de proveedores."],
    ["price_lists.import", "Importar listas de precios", "Permite importar listas de precios desde archivos."],
    ["price_lists.validate", "Validar listas de precios", "Permite validar listas de precios importadas."],
    ["price_lists.approve", "Aprobar listas de precios", "Permite aprobar listas de precios validadas."],
  ]),
  definePermissions("clients", "Clientes", [
    ["clients.read", "Ver clientes", "Permite consultar registros de clientes."],
    ["clients.create", "Crear clientes", "Permite crear registros de clientes."],
    ["clients.update", "Actualizar clientes", "Permite editar registros de clientes."],
    ["clients.delete", "Eliminar clientes", "Permite eliminar registros de clientes."],
  ]),
  definePermissions("projects", "Proyectos", [
    ["projects.read", "Ver proyectos", "Permite consultar registros de proyectos."],
    ["projects.create", "Crear proyectos", "Permite crear registros de proyectos."],
    ["projects.update", "Actualizar proyectos", "Permite editar registros de proyectos."],
    ["projects.delete", "Eliminar proyectos", "Permite eliminar registros de proyectos."],
  ]),
  definePermissions("quotations", "Cotizaciones", [
    ["quotations.read", "Ver cotizaciones", "Permite consultar el listado y detalle de cotizaciones."],
    ["quotations.create", "Crear cotizaciones", "Permite crear cotizaciones."],
    ["quotations.update", "Actualizar cotizaciones", "Permite editar cotizaciones."],
    ["quotations.delete", "Eliminar cotizaciones", "Permite archivar cotizaciones."],
    ["quotations.send", "Enviar cotizaciones", "Permite marcar cotizaciones como enviadas al cliente."],
    ["quotations.approve", "Aprobar cotizaciones", "Permite aprobar cotizaciones."],
    ["quotations.override_cost", "Modificar costos", "Permite modificar valores de costo de una cotización."],
    ["quotations.view_cost", "Ver costos de cotización", "Permite consultar el desglose de costos de cotizaciones."],
    ["quotations.export_pdf", "Exportar cotizaciones", "Permite exportar cotizaciones en PDF."],
  ]),
  definePermissions("inventory", "Inventario", [
    ["inventory.read", "Ver inventario", "Permite consultar existencias, movimientos y remanentes."],
    ["inventory.create", "Crear inventario", "Permite crear registros de inventario."],
    ["inventory.update", "Actualizar inventario", "Permite editar registros de inventario."],
    ["inventory.adjust", "Adjust inventory", "Adjust on-hand stock."],
    ["inventory.reserve", "Reserve inventory", "Reserve stock for downstream work."],
    [
      "inventory.release_reservation",
      "Release reservations",
      "Release or consume reserved stock allocations.",
    ],
    ["inventory.damage", "Report damage", "Mark inventory as damaged for review."],
    ["inventory.scrap", "Scrap inventory", "Scrap unusable inventory balances."],
    [
      "inventory.view_cost",
      "Ver costos de inventario",
      "Permite consultar valores de costo de inventario cuando se expongan.",
    ],
  ]),
  definePermissions("cutting", "Corte", [
    ["cutting.read", "Ver corte", "Permite consultar optimizaciones de vidrio y planes de corte."],
    ["cutting.run", "Ejecutar corte", "Permite ejecutar optimizaciones de láminas de vidrio."],
    ["cutting.approve", "Aprobar corte", "Permite aprobar planes de corte generados."],
    [
      "cutting.create_remnants",
      "Crear remanentes",
      "Permite crear registros de remanentes desde planes de corte aprobados.",
    ],
    ["cutting.print", "Imprimir corte", "Permite consultar diseños de corte imprimibles."],
  ]),
  definePermissions("purchasing", "Compras", [
    [
      "purchasing.read",
      "Ver compras",
      "Permite consultar solicitudes de compra, comparativos, órdenes y recepciones.",
    ],
    [
      "purchasing.create",
      "Crear compras",
      "Permite crear solicitudes, comparativos y registros manuales de compras.",
    ],
    [
      "purchasing.update",
      "Actualizar compras",
      "Permite editar solicitudes, comparativos y órdenes de compra autorizadas.",
    ],
    [
      "purchasing.delete",
      "Eliminar compras",
      "Permite cancelar o archivar registros de compras autorizados.",
    ],
    [
      "purchasing.approve",
      "Aprobar compras",
      "Permite aprobar solicitudes y comparativos de proveedores.",
    ],
    [
      "purchasing.compare_suppliers",
      "Comparar proveedores",
      "Permite ejecutar comparativos y evaluar opciones de abastecimiento.",
    ],
    [
      "purchasing.create_po",
      "Crear órdenes de compra",
      "Permite generar órdenes desde solicitudes o comparativos aprobados.",
    ],
    [
      "purchasing.send_po",
      "Enviar órdenes de compra",
      "Permite marcar órdenes como enviadas a proveedores y avanzar su flujo.",
    ],
    [
      "purchasing.receive",
      "Recibir órdenes de compra",
      "Permite recibir órdenes en inventario y registrar recepciones.",
    ],
    [
      "purchasing.view_cost",
      "Ver costos de compras",
      "Permite consultar costos de proveedores, comparativos y órdenes de compra.",
    ],
  ]),
  definePermissions("production", "Producción", [
    ["production.read", "Ver producción", "Consultar órdenes y estados de producción."],
    [
      "production.create",
      "Crear producción",
      "Crear órdenes y tareas de producción.",
    ],
    ["production.update", "Actualizar producción", "Editar el trabajo de producción."],
    [
      "production.delete",
      "Eliminar producción",
      "Archivar o cancelar órdenes de producción cuando corresponda.",
    ],
    [
      "production.start",
      "Ejecutar producción",
      "Iniciar y pausar órdenes y tareas de producción.",
    ],
    ["production.complete", "Completar producción", "Marcar el trabajo de producción como completado."],
    [
      "production.consume_material",
      "Consumir material",
      "Consumir existencias o remanentes durante la ejecución.",
    ],
    [
      "production.quality_check",
      "Control de calidad",
      "Registrar y aprobar controles de calidad de producción.",
    ],
    [
      "production.view_cost",
      "Ver costos de producción",
      "Consultar costos de materiales cuando estén disponibles.",
    ],
    [
      "production.report_waste",
      "Registrar desperdicio",
      "Calcular y revisar desperdicio teórico frente al real.",
    ],
    ["produccion.tablero.ver", "Ver tablero de producción", "Consultar el tablero operativo centralizado."],
    ["produccion.planificacion.ver", "Ver planificación", "Consultar la planificación y el calendario de producción."],
    ["produccion.planificacion.programar", "Programar producción", "Asignar fechas, centros y responsables a órdenes."],
    ["produccion.planificacion.reprogramar", "Reprogramar producción", "Cambiar fechas programadas dejando motivo y auditoría."],
    ["produccion.tareas.asignar", "Asignar tareas", "Asignar tareas a responsables y centros de trabajo."],
    ["produccion.tareas.ejecutar", "Ejecutar tareas", "Iniciar, pausar, reanudar y bloquear tareas."],
    ["produccion.tareas.completar", "Completar tareas", "Completar tareas que cumplan sus validaciones."],
    ["produccion.prioridad.actualizar", "Actualizar prioridad", "Cambiar la prioridad de una orden con motivo."],
    ["produccion.bloqueos.ver", "Ver bloqueos", "Consultar bloqueos e impacto operativo."],
    ["produccion.bloqueos.crear", "Crear bloqueos", "Registrar bloqueos de órdenes o tareas."],
    ["produccion.bloqueos.resolver", "Resolver bloqueos", "Resolver bloqueos dejando resolución y trazabilidad."],
    ["produccion.centros.ver", "Ver centros de trabajo", "Consultar centros, estados y compatibilidad."],
    ["produccion.centros.configurar", "Configurar centros", "Configurar capacidad, horarios y disponibilidad."],
    ["produccion.capacidad.ver", "Ver capacidad", "Consultar carga y capacidad de centros y responsables."],
    ["produccion.calidad.ver", "Ver calidad", "Consultar controles de calidad de producción."],
    ["produccion.calidad.aprobar", "Aprobar calidad", "Aprobar o rechazar controles de calidad."],
    ["produccion.desperdicios.ver", "Ver desperdicios", "Consultar desperdicios y remanentes generados."],
    ["produccion.desperdicios.registrar", "Registrar desperdicios", "Registrar desperdicios, scrap y remanentes."],
    ["produccion.exportar", "Exportar producción", "Exportar planes y reportes de producción."],
  ]),
  definePermissions("installations", "Instalaciones", [
    [
      "installations.view",
      "Ver instalaciones",
      "Ver la programacion y la ejecucion de instalaciones.",
    ],
    [
      "installations.create",
      "Crear instalaciones",
      "Crear ordenes de instalacion desde proyectos o cotizaciones.",
    ],
    [
      "installations.update",
      "Actualizar instalaciones",
      "Editar ordenes, tareas, observaciones y datos operativos.",
    ],
    [
      "installations.schedule",
      "Programar instalaciones",
      "Programar o reprogramar fechas, horarios y ventanas de trabajo.",
    ],
    [
      "installations.assign",
      "Asignar instalaciones",
      "Asignar cuadrillas y supervisores a ordenes de instalacion.",
    ],
    [
      "installations.execute",
      "Ejecutar instalaciones",
      "Registrar salida a ruta, inicio de trabajo, evidencias e incidencias.",
    ],
    [
      "installations.complete",
      "Completar instalaciones",
      "Cerrar instalaciones y marcar tareas como completadas.",
    ],
    [
      "installations.cancel",
      "Cancelar instalaciones",
      "Cancelar ordenes de instalacion cuando corresponda.",
    ],
    [
      "installations.export",
      "Exportar instalaciones",
      "Exportar cronogramas y reportes de instalacion.",
    ],
  ]),
  definePermissions("mediciones", "Mediciones", [
    [
      "mediciones.ver",
      "Ver mediciones",
      "Ver solicitudes de medicion, visitas tecnicas, medidas y evidencias.",
    ],
    [
      "mediciones.crear",
      "Crear mediciones",
      "Crear solicitudes de medicion y registros iniciales asociados.",
    ],
    [
      "mediciones.actualizar",
      "Actualizar mediciones",
      "Editar datos operativos, medidas, observaciones y programacion.",
    ],
    [
      "mediciones.programar",
      "Programar mediciones",
      "Programar o reprogramar visitas tecnicas, fechas y horarios.",
    ],
    [
      "mediciones.asignar",
      "Asignar tecnicos",
      "Asignar tecnicos responsables a solicitudes y visitas tecnicas.",
    ],
    [
      "mediciones.ejecutar",
      "Ejecutar mediciones",
      "Iniciar visitas, registrar medidas, evidencias y observaciones tecnicas.",
    ],
    [
      "mediciones.aprobar",
      "Aprobar mediciones",
      "Aprobar mediciones y habilitarlas para cotizacion y produccion.",
    ],
    [
      "mediciones.rechazar",
      "Rechazar mediciones",
      "Rechazar mediciones y solicitar correcciones o reprogramacion.",
    ],
    [
      "mediciones.exportar",
      "Exportar mediciones",
      "Exportar reportes PDF y Excel del modulo de mediciones.",
    ],
  ]),
  definePermissions("rentabilidad", "Rentabilidad", [
    [
      "rentabilidad.ver",
      "Ver rentabilidad",
      "Ver rentabilidad, margenes y tableros financieros por proyecto.",
    ],
    [
      "rentabilidad.analizar",
      "Analizar rentabilidad",
      "Analizar variaciones, costos reales, desperdicio y alertas del proyecto.",
    ],
    [
      "rentabilidad.exportar",
      "Exportar rentabilidad",
      "Exportar reportes PDF y Excel del modulo de rentabilidad.",
    ],
  ]),
  definePermissions("postventa", "Postventa", [
    [
      "postventa.ver",
      "Ver postventa",
      "Ver casos postventa, actividades, evidencias, costos y cierres.",
    ],
    [
      "postventa.crear",
      "Crear casos postventa",
      "Registrar casos postventa desde clientes, proyectos o instalaciones.",
    ],
    [
      "postventa.actualizar",
      "Actualizar postventa",
      "Editar descripcion, solucion, actividades, evidencias y costos postventa.",
    ],
    [
      "postventa.asignar",
      "Asignar responsables",
      "Asignar o reasignar responsables a casos y actividades postventa.",
    ],
    [
      "postventa.cerrar",
      "Cerrar casos postventa",
      "Resolver y cerrar casos postventa con su historial correspondiente.",
    ],
    [
      "postventa.exportar",
      "Exportar postventa",
      "Exportar reportes PDF y Excel de casos y costos postventa.",
    ],
  ]),
  definePermissions("garantias", "Garantias", [
    [
      "garantias.ver",
      "Ver garantias",
      "Ver garantias registradas por proyecto, cliente y vigencia.",
    ],
    [
      "garantias.crear",
      "Crear garantias",
      "Registrar condiciones y vigencias de garantia por proyecto.",
    ],
    [
      "garantias.actualizar",
      "Actualizar garantias",
      "Editar condiciones, vigencias y estado de las garantias registradas.",
    ],
  ]),
  definePermissions("portal_cliente", "Portal del Cliente", [
    [
      "portal_cliente.ver",
      "Ver portal del cliente",
      "Ver accesos, actividad, documentos y mensajes del Portal del Cliente.",
    ],
    [
      "portal_cliente.configurar",
      "Configurar portal del cliente",
      "Configurar usuarios cliente, proyectos habilitados y parametros del portal.",
    ],
    [
      "portal_cliente.invitar",
      "Invitar clientes",
      "Invitar clientes al portal y reenviar accesos de activacion.",
    ],
    [
      "portal_cliente.bloquear",
      "Bloquear accesos cliente",
      "Bloquear, reactivar o dejar inactivo el acceso de clientes al portal.",
    ],
    [
      "portal_cliente.documentos",
      "Gestionar documentos del portal",
      "Subir y publicar documentos visibles para el cliente.",
    ],
    [
      "portal_cliente.mensajes",
      "Gestionar mensajes del portal",
      "Responder y revisar conversaciones del cliente por proyecto.",
    ],
  ]),
  definePermissions("tableros", "Tableros", [
    [
      "tableros.ver",
      "Ver tableros",
      "Ver paneles ejecutivos, indicadores integrados y vistas consolidadas del negocio.",
    ],
    [
      "tableros.configurar",
      "Configurar tableros",
      "Configurar estructura, visibilidad y composicion de los tableros ejecutivos.",
    ],
    [
      "tableros.exportar",
      "Exportar tableros",
      "Exportar paneles ejecutivos en formatos PDF y Excel.",
    ],
  ]),
  definePermissions("indicadores", "Indicadores", [
    [
      "indicadores.ver",
      "Ver indicadores",
      "Ver indicadores comerciales, operativos, financieros, productivos y de postventa.",
    ],
    [
      "indicadores.configurar",
      "Configurar indicadores",
      "Definir formulas, metas, responsables y comportamiento de indicadores de gestion.",
    ],
  ]),
  definePermissions("reportes", "Reportes", [
    [
      "reportes.ver",
      "Ver reportes",
      "Ver reportes ejecutivos y salidas de inteligencia de negocio.",
    ],
    [
      "reportes.exportar",
      "Exportar reportes",
      "Exportar reportes ejecutivos y datos base en PDF y Excel.",
    ],
  ]),
  definePermissions("reports", "Reportes heredados", [
    [
      "reports.read",
      "Ver reportes heredados",
      "Permiso heredado para mantener compatibilidad con accesos historicos de reportes.",
    ],
    [
      "reports.export",
      "Exportar reportes heredados",
      "Permiso heredado para mantener compatibilidad con exportaciones historicas.",
    ],
  ]),
  definePermissions("portal_operativo", "Portal Operativo", [
    [
      "portal_operativo.acceder",
      "Acceder al Portal Operativo",
      "Permite entrar al espacio de trabajo operativo responsivo.",
    ],
    [
      "operaciones.almacen.ver",
      "Ver almacén operativo",
      "Consultar existencias, reservas y ubicaciones desde el Portal Operativo.",
    ],
    [
      "operaciones.almacen.movimientos",
      "Registrar movimientos de almacén",
      "Registrar entradas, salidas, transferencias y ajustes autorizados.",
    ],
    [
      "operaciones.almacen.preparar",
      "Preparar materiales",
      "Preparar solicitudes y confirmar faltantes o entregas.",
    ],
    [
      "operaciones.almacen.entregar",
      "Entregar materiales",
      "Confirmar entregas de materiales a producción o instalación.",
    ],
    [
      "operaciones.produccion.ver",
      "Ver producción operativa",
      "Consultar órdenes, tareas, prioridades y avance de producción.",
    ],
    [
      "operaciones.produccion.ejecutar",
      "Ejecutar producción",
      "Iniciar, pausar, reanudar y completar trabajo de producción.",
    ],
    [
      "operaciones.produccion.consumir_material",
      "Consumir material en producción",
      "Registrar consumo real de materiales en una tarea.",
    ],
    [
      "operaciones.produccion.reportar_desperdicio",
      "Reportar desperdicio",
      "Registrar desperdicios, piezas defectuosas y remanentes.",
    ],
    [
      "operaciones.mediciones.ver",
      "Ver mediciones operativas",
      "Consultar la agenda y los registros técnicos de medición.",
    ],
    [
      "operaciones.mediciones.ejecutar",
      "Ejecutar mediciones",
      "Iniciar visitas y registrar medidas, observaciones y evidencias.",
    ],
    [
      "operaciones.mediciones.enviar_revision",
      "Enviar mediciones a revisión",
      "Enviar registros técnicos para aprobación o corrección.",
    ],
    [
      "operaciones.instalaciones.ver",
      "Ver instalaciones operativas",
      "Consultar agenda, equipos, tareas y estado de instalaciones.",
    ],
    [
      "operaciones.instalaciones.ejecutar",
      "Ejecutar instalaciones",
      "Actualizar el avance de instalaciones y registrar evidencias.",
    ],
    [
      "operaciones.instalaciones.completar",
      "Completar instalaciones",
      "Cerrar instalaciones después de validar tareas y conformidad.",
    ],
    [
      "operaciones.incidencias.ver",
      "Ver incidencias",
      "Consultar incidencias operativas y su trazabilidad.",
    ],
    [
      "operaciones.incidencias.crear",
      "Crear incidencias",
      "Reportar incidencias desde almacén, producción, medición o instalación.",
    ],
    [
      "operaciones.incidencias.actualizar",
      "Actualizar incidencias",
      "Asignar, atender, resolver y cerrar incidencias autorizadas.",
    ],
    [
      "operaciones.calidad.ver",
      "Ver control de calidad",
      "Consultar inspecciones, listas de verificación y resultados.",
    ],
    [
      "operaciones.calidad.ejecutar",
      "Ejecutar control de calidad",
      "Completar ítems, observaciones y evidencias de calidad.",
    ],
    [
      "operaciones.calidad.aprobar",
      "Aprobar control de calidad",
      "Aprobar o rechazar controles de calidad completos.",
    ],
    [
      "operaciones.supervision.ver",
      "Ver supervisión operativa",
      "Consultar carga de trabajo, alertas y actividades en curso.",
    ],
    [
      "operaciones.supervision.reasignar",
      "Reasignar tareas",
      "Reasignar tareas y responsables cuando esté autorizado.",
    ],
    [
      "operaciones.supervision.aprobar",
      "Aprobar trabajo operativo",
      "Revisar evidencias, solicitar correcciones y aprobar trabajo.",
    ],
  ]),
] as const satisfies readonly PermissionGroupDefinition[];

export const PERMISSION_DEFINITIONS = PERMISSION_GROUPS.flatMap(
  (group) => group.permissions,
);

export const PERMISSION_KEYS = PERMISSION_DEFINITIONS.map(
  (permission) => permission.key,
);

export const PERMISSION_KEY_SET = new Set(PERMISSION_KEYS);

export const PERMISSION_DEFINITION_BY_KEY = new Map(
  PERMISSION_DEFINITIONS.map((permission) => [permission.key, permission] as const),
);

export const CRITICAL_ADMIN_PERMISSIONS = [...PERMISSION_KEYS];

export const ADMIN_LIKE_ROLE_NAMES = [
  SUPER_ADMIN_ROLE_NAME,
  ADMIN_ROLE_NAME,
] as const;

export const READ_ONLY_PERMISSION_KEYS = [
  ...PERMISSION_KEYS.filter(
    (permission) =>
      permission.endsWith(".read") ||
      permission.endsWith(".view") ||
      permission.endsWith(".ver"),
  ),
  "reports.export",
] as const;

const withoutPermissions = (
  permissions: readonly string[],
  removedPermissions: readonly string[],
): string[] => {
  const removedPermissionSet = new Set(removedPermissions);
  return permissions.filter((permission) => !removedPermissionSet.has(permission));
};

const uniquePermissions = (permissions: readonly string[]): string[] => {
  return Array.from(new Set(permissions)).sort((left, right) =>
    left.localeCompare(right),
  );
};

export const ROLE_DEFINITIONS: Array<{
  description: string;
  name: ErpRoleName;
  permissionKeys: string[];
}> = [
  {
    description: "Acceso completo a la plataforma y todos los módulos del ERP.",
    name: SUPER_ADMIN_ROLE_NAME,
    permissionKeys: uniquePermissions(PERMISSION_KEYS),
  },
  {
    description:
      "Acceso operativo amplio, excepto las acciones administrativas más sensibles.",
    name: ADMIN_ROLE_NAME,
    permissionKeys: uniquePermissions(
      withoutPermissions(PERMISSION_KEYS, [
        "system.settings.update",
        "system.users.delete",
      ]),
    ),
  },
  {
    description:
      "Acceso de gerencia para supervisión operativa, aprobación de cotizaciones y reportes.",
    name: MANAGER_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "portal_operativo.acceder",
      "operaciones.calidad.aprobar",
      "operaciones.calidad.ejecutar",
      "operaciones.calidad.ver",
      "operaciones.incidencias.actualizar",
      "operaciones.incidencias.crear",
      "operaciones.incidencias.ver",
      "operaciones.instalaciones.completar",
      "operaciones.instalaciones.ejecutar",
      "operaciones.instalaciones.ver",
      "operaciones.mediciones.enviar_revision",
      "operaciones.mediciones.ejecutar",
      "operaciones.mediciones.ver",
      "operaciones.produccion.ejecutar",
      "operaciones.produccion.reportar_desperdicio",
      "operaciones.produccion.ver",
      "produccion.tablero.ver",
      "produccion.planificacion.ver",
      "produccion.capacidad.ver",
      "produccion.centros.ver",
      "produccion.bloqueos.ver",
      "produccion.calidad.ver",
      "produccion.desperdicios.ver",
      "produccion.planificacion.programar",
      "produccion.planificacion.reprogramar",
      "produccion.bloqueos.resolver",
      "produccion.calidad.aprobar",
      "operaciones.supervision.aprobar",
      "operaciones.supervision.reasignar",
      "operaciones.supervision.ver",
      "operaciones.almacen.entregar",
      "operaciones.almacen.movimientos",
      "operaciones.almacen.preparar",
      "operaciones.almacen.ver",
      "clients.create",
      "clients.read",
      "clients.update",
      "installations.assign",
      "installations.cancel",
      "installations.complete",
      "installations.create",
      "installations.execute",
      "installations.export",
      "installations.schedule",
      "installations.update",
      "installations.view",
      "inventory.read",
      "inventory.reserve",
      "inventory.release_reservation",
      "inventory.view_cost",
      "materials.read",
      "mediciones.aprobar",
      "mediciones.asignar",
      "mediciones.actualizar",
      "mediciones.crear",
      "mediciones.ejecutar",
      "mediciones.exportar",
      "mediciones.programar",
      "mediciones.rechazar",
      "mediciones.ver",
      "cutting.approve",
      "cutting.print",
      "cutting.read",
      "cutting.run",
      "garantias.actualizar",
      "garantias.crear",
      "garantias.ver",
      "price_lists.read",
      "postventa.actualizar",
      "postventa.asignar",
      "postventa.cerrar",
      "postventa.crear",
      "postventa.exportar",
      "postventa.ver",
      "portal_cliente.bloquear",
      "portal_cliente.configurar",
      "portal_cliente.documentos",
      "portal_cliente.invitar",
      "portal_cliente.mensajes",
      "portal_cliente.ver",
      "production.complete",
      "production.consume_material",
      "production.create",
      "production.quality_check",
      "production.read",
      "production.report_waste",
      "production.start",
      "production.update",
      "production.view_cost",
      "projects.create",
      "projects.read",
      "projects.update",
      "purchasing.approve",
      "purchasing.compare_suppliers",
      "purchasing.create_po",
      "purchasing.read",
      "purchasing.view_cost",
      "quotations.approve",
      "quotations.create",
      "quotations.delete",
      "quotations.export_pdf",
      "quotations.override_cost",
      "quotations.read",
      "quotations.send",
      "quotations.update",
      "quotations.view_cost",
      "rentabilidad.analizar",
      "rentabilidad.exportar",
      "rentabilidad.ver",
      "reports.export",
      "reports.read",
      "suppliers.read",
    ]),
  },
  {
    description: "Acceso comercial para clientes, proyectos, cotizaciones y reportes.",
    name: SALES_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "clients.create",
      "clients.read",
      "clients.update",
      "inventory.read",
      "inventory.reserve",
      "cutting.print",
      "cutting.read",
      "cutting.run",
      "materials.read",
      "mediciones.actualizar",
      "mediciones.crear",
      "mediciones.exportar",
      "mediciones.programar",
      "mediciones.ver",
      "price_lists.read",
      "garantias.ver",
      "postventa.actualizar",
      "postventa.crear",
      "postventa.exportar",
      "postventa.ver",
      "portal_cliente.configurar",
      "portal_cliente.documentos",
      "portal_cliente.invitar",
      "portal_cliente.mensajes",
      "portal_cliente.ver",
      "projects.create",
      "projects.read",
      "projects.update",
      "quotations.create",
      "quotations.delete",
      "quotations.export_pdf",
      "quotations.read",
      "quotations.send",
      "quotations.update",
      "rentabilidad.exportar",
      "rentabilidad.ver",
      "reports.export",
      "reports.read",
    ]),
  },
  {
    description:
      "Acceso de compras para proveedores, materiales, listas de precios y flujos de adquisición.",
    name: PURCHASING_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "cutting.read",
      "cutting.run",
      "inventory.read",
      "materials.create",
      "materials.read",
      "materials.update",
      "price_lists.approve",
      "price_lists.import",
      "price_lists.read",
      "price_lists.validate",
      "purchasing.approve",
      "purchasing.compare_suppliers",
      "purchasing.create",
      "purchasing.create_po",
      "purchasing.delete",
      "purchasing.read",
      "purchasing.receive",
      "purchasing.send_po",
      "purchasing.update",
      "purchasing.view_cost",
      "reports.export",
      "reports.read",
      "suppliers.create",
      "suppliers.read",
      "suppliers.update",
    ]),
  },
  {
    description: "Acceso de almacén para control de inventario, recepciones y reservas.",
    name: WAREHOUSE_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "portal_operativo.acceder",
      "operaciones.almacen.entregar",
      "operaciones.almacen.movimientos",
      "operaciones.almacen.preparar",
      "operaciones.almacen.ver",
      "cutting.create_remnants",
      "cutting.print",
      "cutting.read",
      "inventory.adjust",
      "inventory.create",
      "inventory.damage",
      "inventory.read",
      "inventory.release_reservation",
      "inventory.reserve",
      "inventory.scrap",
      "inventory.update",
      "materials.read",
      "mediciones.exportar",
      "mediciones.ver",
      "purchasing.read",
      "purchasing.receive",
      "reports.read",
    ]),
  },
  {
    description:
      "Acceso de planta para reservas, optimizaciones y cierre de producción.",
    name: PRODUCTION_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "portal_operativo.acceder",
      "operaciones.calidad.ejecutar",
      "operaciones.calidad.ver",
      "operaciones.incidencias.crear",
      "operaciones.incidencias.ver",
      "operaciones.produccion.consumir_material",
      "operaciones.produccion.ejecutar",
      "operaciones.produccion.reportar_desperdicio",
      "operaciones.produccion.ver",
      "operaciones.almacen.ver",
      "inventory.read",
      "inventory.release_reservation",
      "inventory.reserve",
      "materials.read",
      "mediciones.exportar",
      "mediciones.ver",
      "cutting.create_remnants",
      "cutting.print",
      "cutting.read",
      "cutting.run",
      "production.complete",
      "production.consume_material",
      "production.create",
      "production.quality_check",
      "production.read",
      "production.report_waste",
      "production.start",
      "production.update",
      "produccion.tablero.ver",
      "produccion.planificacion.ver",
      "produccion.planificacion.programar",
      "produccion.planificacion.reprogramar",
      "produccion.tareas.asignar",
      "produccion.tareas.ejecutar",
      "produccion.tareas.completar",
      "produccion.prioridad.actualizar",
      "produccion.bloqueos.ver",
      "produccion.bloqueos.crear",
      "produccion.bloqueos.resolver",
      "produccion.centros.ver",
      "produccion.centros.configurar",
      "produccion.capacidad.ver",
      "produccion.calidad.ver",
      "produccion.calidad.aprobar",
      "produccion.desperdicios.ver",
      "produccion.desperdicios.registrar",
      "produccion.exportar",
      "projects.read",
      "reports.read",
    ]),
  },
  {
    description:
      "Acceso de campo para asignaciones, avances de ejecución y contexto de proyectos.",
    name: INSTALLATION_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "portal_operativo.acceder",
      "operaciones.incidencias.crear",
      "operaciones.incidencias.ver",
      "operaciones.instalaciones.completar",
      "operaciones.instalaciones.ejecutar",
      "operaciones.instalaciones.ver",
      "operaciones.mediciones.ejecutar",
      "operaciones.mediciones.enviar_revision",
      "operaciones.mediciones.ver",
      "clients.read",
      "mediciones.actualizar",
      "mediciones.asignar",
      "mediciones.ejecutar",
      "mediciones.exportar",
      "mediciones.programar",
      "mediciones.ver",
      "garantias.ver",
      "installations.assign",
      "installations.complete",
      "installations.execute",
      "installations.export",
      "installations.schedule",
      "installations.update",
      "installations.view",
      "postventa.actualizar",
      "postventa.asignar",
      "postventa.cerrar",
      "postventa.crear",
      "postventa.exportar",
      "postventa.ver",
      "projects.read",
      "quotations.read",
      "reports.read",
    ]),
  },
  {
    description:
      "Acceso financiero para márgenes, compras, reportes y auditoría operativa.",
    name: ACCOUNTING_ROLE_NAME,
    permissionKeys: uniquePermissions([
      "clients.read",
      "cutting.print",
      "cutting.read",
      "inventory.read",
      "inventory.view_cost",
      "mediciones.exportar",
      "mediciones.ver",
      "garantias.ver",
      "postventa.exportar",
      "postventa.ver",
      "projects.read",
      "purchasing.read",
      "purchasing.view_cost",
      "quotations.export_pdf",
      "quotations.read",
      "quotations.view_cost",
      "rentabilidad.analizar",
      "rentabilidad.exportar",
      "rentabilidad.ver",
      "reports.export",
      "reports.read",
      "system.audit.read",
    ]),
  },
  {
    description: "Consulta sin edición de registros, reportes y tableros.",
    name: READ_ONLY_ROLE_NAME,
    permissionKeys: uniquePermissions(READ_ONLY_PERMISSION_KEYS),
  },
] as const;

export const MODULE_REGISTRY_SEED = [
  {
    description: "Vista operativa y accesos directos del ERP.",
    icon: "LayoutDashboard",
    isEnabled: true,
    key: "dashboard",
    label: "Panel principal",
    requiredPermission: null,
    route: "/admin",
    sortOrder: 10,
  },
  {
    description: "Directorio de proveedores y ciclo de vida de aliados de compras.",
    icon: "Truck",
    isEnabled: true,
    key: "suppliers",
    label: "Proveedores",
    requiredPermission: "suppliers.read",
    route: "/admin/suppliers",
    sortOrder: 20,
  },
  {
    description: "Catálogo y administración de perfiles de materiales.",
    icon: "Boxes",
    isEnabled: true,
    key: "materials",
    label: "Materiales",
    requiredPermission: "materials.read",
    route: "/admin/materials",
    sortOrder: 30,
  },
  {
    description: "Árbol de categorías para organizar el catálogo maestro de materiales.",
    icon: "FolderTree",
    isEnabled: true,
    key: "material-categories",
    label: "Categorías de materiales",
    requiredPermission: "materials.read",
    route: "/admin/material-categories",
    sortOrder: 35,
  },
  {
    description: "Códigos de proveedor vinculados a materiales internos con seguimiento de confianza.",
    icon: "Waypoints",
    isEnabled: true,
    key: "supplier-material-equivalences",
    label: "Equivalencias de proveedor",
    requiredPermission: "materials.read",
    route: "/admin/supplier-material-equivalences",
    sortOrder: 37,
  },
  {
    description: "Listas de precios de proveedores importadas y estado de aprobación.",
    icon: "FileSpreadsheet",
    isEnabled: true,
    key: "price-lists",
    label: "Listas de precios",
    requiredPermission: "price_lists.read",
    route: "/admin/price-lists",
    sortOrder: 40,
  },
  {
    description: "Cambios históricos de precios de proveedores en importaciones aprobadas.",
    icon: "ChartColumn",
    isEnabled: true,
    key: "price-history",
    label: "Historial de precios",
    requiredPermission: "price_lists.read",
    route: "/admin/price-lists/price-history",
    sortOrder: 42,
  },
  {
    description: "Empresas cliente, contactos y contexto comercial.",
    icon: "Users",
    isEnabled: true,
    key: "clients",
    label: "Clientes",
    requiredPermission: "clients.read",
    route: "/admin/clients",
    sortOrder: 50,
  },
  {
    description: "Invitaciones, documentos y conversaciones del portal externo del cliente.",
    icon: "MonitorSmartphone",
    isEnabled: true,
    key: "portal-cliente",
    label: "Portal del Cliente",
    requiredPermission: "portal_cliente.ver",
    route: "/admin/portal-clientes",
    sortOrder: 52,
  },
  {
    description: "Registros de proyectos desde el ingreso hasta la instalación.",
    icon: "FolderKanban",
    isEnabled: true,
    key: "projects",
    label: "Proyectos",
    requiredPermission: "projects.read",
    route: "/admin/projects",
    sortOrder: 60,
  },
  {
    description: "Solicitudes de medicion, visitas tecnicas, registro en obra y aprobacion de medidas.",
    icon: "Ruler",
    isEnabled: true,
    key: "measurements",
    label: "Mediciones",
    requiredPermission: "mediciones.ver",
    route: "/admin/mediciones",
    sortOrder: 63,
  },
  {
    description:
      "Plantillas de producto reutilizables y reglas de cálculo para cotizaciones y producción.",
    icon: "PanelsTopLeft",
    isEnabled: true,
    key: "product-templates",
    label: "Plantillas de producto",
    requiredPermission: "quotations.create",
    route: "/admin/product-templates",
    sortOrder: 65,
  },
  {
    description: "Espacio de cotizaciones y flujo de aprobación.",
    icon: "FileText",
    isEnabled: true,
    key: "quotations",
    label: "Cotizaciones",
    requiredPermission: "quotations.read",
    route: "/admin/quotations",
    sortOrder: 70,
  },
  {
    description: "Existencias, reservas, daños y visibilidad de inventario.",
    icon: "Warehouse",
    isEnabled: true,
    key: "inventory",
    label: "Inventario",
    requiredPermission: "inventory.read",
    route: "/admin/inventory",
    sortOrder: 80,
  },
  {
    description: "Seguimiento de remanentes reutilizables y sobrantes.",
    icon: "Scissors",
    isEnabled: true,
    key: "remnants",
    label: "Remanentes",
    requiredPermission: "inventory.read",
    route: "/admin/inventory/remnants",
    sortOrder: 90,
  },
  {
    description: "Optimizaciones de vidrio, planes de corte y planificación de remanentes.",
    icon: "Gauge",
    isEnabled: true,
    key: "optimization",
    label: "Corte",
    requiredPermission: "cutting.read",
    route: "/cutting",
    sortOrder: 100,
  },
  {
    description: "Optimización de perfiles de aluminio, planes de corte y preparación de ejecución.",
    icon: "Ruler",
    isEnabled: true,
    key: "profile-optimization",
    label: "Optimización de perfiles",
    requiredPermission: "cutting.read",
    route: "/operations/profile-optimization",
    sortOrder: 105,
  },
  {
    description: "Solicitudes de compra, comparativos, órdenes y recepciones.",
    icon: "ShoppingCart",
    isEnabled: true,
    key: "purchases",
    label: "Compras",
    requiredPermission: "purchasing.read",
    route: "/purchasing",
    sortOrder: 110,
  },
  {
    description: "Planificación, ejecución y estado de producción.",
    icon: "Hammer",
    isEnabled: true,
    key: "production",
    label: "Producción",
    requiredPermission: "production.read",
    route: "/production",
    sortOrder: 120,
  },
  {
    description: "Programacion, asignacion de cuadrillas y ejecucion en campo.",
    icon: "Wrench",
    isEnabled: true,
    key: "installation",
    label: "Instalaciones",
    requiredPermission: "installations.view",
    route: "/admin/installation",
    sortOrder: 130,
  },
  {
    description:
      "Garantias, reclamos postventa, reposiciones, evidencias, costos e impacto financiero por caso.",
    icon: "ShieldCheck",
    isEnabled: true,
    key: "postventa",
    label: "Postventa",
    requiredPermission: "postventa.ver",
    route: "/admin/postventa",
    sortOrder: 134,
  },
  {
    description:
      "Rentabilidad real, presupuestos, variaciones, desperdicio y exportaciones financieras.",
    icon: "LineChart",
    isEnabled: true,
    key: "rentabilidad",
    label: "Rentabilidad",
    requiredPermission: "rentabilidad.ver",
    route: "/admin/rentabilidad",
    sortOrder: 138,
  },
  {
    description: "Panel ejecutivo, inteligencia de negocio y exportaciones gerenciales.",
    icon: "BarChart3",
    isEnabled: true,
    key: "reports",
    label: "Tableros ejecutivos",
    requiredPermission: "reports.read",
    route: "/admin/tableros",
    sortOrder: 140,
  },
  {
    description: "Configuración general y parámetros del ERP.",
    icon: "Settings",
    isEnabled: true,
    key: "settings",
    label: "Configuración",
    requiredPermission: "system.settings.read",
    route: "/admin/settings",
    sortOrder: 150,
  },
  {
    description: "Historial inmutable de auditoría para cambios privilegiados.",
    icon: "ScrollText",
    isEnabled: true,
    key: "audit-log",
    label: "Auditoría",
    requiredPermission: "system.audit.read",
    route: "/admin/audit-log",
    sortOrder: 160,
  },
] as const;

export const DEFAULT_SYSTEM_SETTINGS = [
  {
    description: "Perfil de empresa utilizado por los módulos del ERP.",
    key: "company.profile",
    valueJson: {
      countryCode: "BO",
      currencyCode: "USD",
      address: "",
      legalName: "Smart Glass Bolivia",
      phone: "",
      taxId: "",
      tradeName: "Smart Glass Bolivia",
    },
  },
  {
    description: "Valores predeterminados de idioma, fechas, medidas y zonas horarias.",
    key: "erp.localization",
    valueJson: {
      dateFormat: "YYYY-MM-DD",
      measurementUnit: "mm",
      numberLocale: "es-BO",
      timezone: "America/La_Paz",
    },
  },
  {
    description: "Controles de flujo para módulos del ERP.",
    key: "erp.features",
    valueJson: {
      installationSchedulingEnabled: true,
      optimizationApprovalRequired: true,
      remnantsTrackingEnabled: true,
    },
  },
  {
    description:
      "Define si se exige al menos una evidencia de campo antes de completar una instalacion.",
    key: "installation.require_evidence_before_completion",
    valueJson: false,
  },
  {
    description: "Margen mínimo de cotización antes de exigir aprobación.",
    key: "quotation.minimum_margin_percent",
    valueJson: 15,
  },
  {
    description: "Descuento máximo de cotización antes de exigir aprobación.",
    key: "quotation.maximum_discount_percent",
    valueJson: 10,
  },
  {
    description: "Indica si los cambios manuales de costos requieren aprobación.",
    key: "quotation.require_approval_for_manual_override",
    valueJson: true,
  },
  {
    description: "Horas predeterminadas antes de que venza una reserva blanda de inventario.",
    key: "inventory.soft_reservation_hours",
    valueJson: 48,
  },
  {
    description: "Ancho predeterminado de respaldo para optimización de láminas en milímetros.",
    key: "cutting.default_sheet_width_mm",
    valueJson: 3210,
  },
  {
    description: "Alto predeterminado de respaldo para optimización de láminas en milímetros.",
    key: "cutting.default_sheet_height_mm",
    valueJson: 2250,
  },
  {
    description: "Permiso global predeterminado de rotación para optimización de corte.",
    key: "cutting.default_allow_rotation",
    valueJson: true,
  },
  {
    description: "Indica si el corte debe priorizar remanentes reutilizables.",
    key: "cutting.prefer_remnants",
    valueJson: true,
  },
  {
    description: "Área mínima de remanente en metros cuadrados para crear remanentes planificados.",
    key: "cutting.minimum_remnant_area_m2",
    valueJson: 0.1,
  },
  {
    description: "Tiempo máximo permitido para una optimización heurística de corte.",
    key: "cutting.max_optimization_runtime_seconds",
    valueJson: 10,
  },
  {
    description: "Indica si los flujos de corte deben priorizar remanentes reutilizables.",
    key: "inventory.prefer_remnants_for_cutting",
    valueJson: true,
  },
  {
    description: "Área mínima de remanente reutilizable en metros cuadrados.",
    key: "inventory.minimum_remnant_area_m2",
    valueJson: 0.1,
  },
  {
    description: "Indica si la optimización de perfiles debe priorizar remanentes lineales.",
    key: "inventory.prefer_profile_remnants",
    valueJson: true,
  },
  {
    description: "Longitud mínima de remanente de perfil reutilizable en milímetros.",
    key: "inventory.minimum_profile_remnant_mm",
    valueJson: 300,
  },
  {
    description: "Indica si los comparativos deben priorizar un único proveedor.",
    key: "purchasing.prefer_single_supplier",
    valueJson: false,
  },
  {
    description: "Identificador de la configuración de evaluación usada en comparativos.",
    key: "purchasing.default_supplier_scoring_config_id",
    valueJson: null,
  },
  {
    description: "Indica si las solicitudes deben aprobarse antes de crear órdenes de compra.",
    key: "purchasing.require_approval_before_po",
    valueJson: true,
  },
] as const;

export const isAdminRoleName = (roleName: string): boolean => {
  return (ADMIN_LIKE_ROLE_NAMES as readonly string[]).includes(roleName);
};

export const isSuperAdminRoleName = (roleName: string): boolean => {
  return roleName === SUPER_ADMIN_ROLE_NAME;
};

export const isPermissionKeyKnown = (permissionKey: string): boolean => {
  return PERMISSION_KEY_SET.has(permissionKey);
};
